/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasidatabase;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author 100 Mbps
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("latihan_db?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        biodataMhsQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT b FROM BiodataMhs b");
        biodataMhsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : biodataMhsQuery.getResultList();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBiodatamhs = new javax.swing.JTable();
        btnTambahData = new javax.swing.JButton();
        btnUbahData = new javax.swing.JButton();
        btnHapusData = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNIM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTANGGALLAHIR = new javax.swing.JTextField();
        rbL = new javax.swing.JRadioButton();
        rbP = new javax.swing.JRadioButton();
        txtNAMA = new javax.swing.JTextField();
        txtFAKULTAS = new javax.swing.JTextField();
        txtJURUSAN = new javax.swing.JTextField();
        txtANGKATAN = new javax.swing.JTextField();
        txtALAMAT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, biodataMhsList, tblBiodatamhs);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nim}"));
        columnBinding.setColumnName("NIM");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nama}"));
        columnBinding.setColumnName("NAMA");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${jenisKelamin}"));
        columnBinding.setColumnName("JENIS KELAMIN");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tanggalLahir}"));
        columnBinding.setColumnName("TANGGAL LAHIR");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${alamat}"));
        columnBinding.setColumnName("ALAMAT");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fakultas}"));
        columnBinding.setColumnName("FAKULTAS");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${jurusan}"));
        columnBinding.setColumnName("JURUSAN");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${angkatan}"));
        columnBinding.setColumnName("ANGKATAN");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tblBiodatamhs);

        btnTambahData.setText("Tambah");
        btnTambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDataActionPerformed(evt);
            }
        });

        btnUbahData.setText("Ubah");
        btnUbahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahDataActionPerformed(evt);
            }
        });

        btnHapusData.setText("Hapus");
        btnHapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusDataActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("NIM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("NAMA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("JENIS KELAMIN");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("TANGGAL LAHIR");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("ALAMAT");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("FAKULTAS");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("JURUSAN");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("ANGKATAN");

        txtTANGGALLAHIR.setToolTipText("");
        txtTANGGALLAHIR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTANGGALLAHIRFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTANGGALLAHIRFocusLost(evt);
            }
        });

        buttonGroup1.add(rbL);
        rbL.setText("L");

        buttonGroup1.add(rbP);
        rbP.setText("P");

        txtALAMAT.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTANGGALLAHIR)
                            .addComponent(txtJURUSAN)
                            .addComponent(txtFAKULTAS)
                            .addComponent(txtANGKATAN)
                            .addComponent(txtALAMAT, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(88, 88, 88)
                                .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(rbL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbP))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTambahData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUbahData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapusData, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rbL)
                            .addComponent(rbP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTANGGALLAHIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtFAKULTAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtJURUSAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnTambahData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUbahData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapusData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtANGKATAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
            
    private void btnTambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDataActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            final String username = "root";
            final String password = "";
            final Connection koneksi = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/latihan_db", username, password);
            
            System.out.println("Koneksi Berhasil");
            
            String input = "INSERT INTO biodata_mhs (nim,nama,jenis_kelamin,"
                    + "tanggal_lahir,alamat,fakultas,jurusan,angkatan)"
                    + "VALUES (?,?,?,?,?,?,?,?)";
            
            PreparedStatement inputdata = koneksi.prepareStatement(input);
            inputdata.setString(1, txtNIM.getText().trim());
            inputdata.setString(2, txtNAMA.getText().trim());
            String jeniskelamin = null;
            if (rbL.isSelected()){
                jeniskelamin = rbL.getText();
            } else {
                jeniskelamin = rbP.getText();
            }
            inputdata.setString(3, jeniskelamin.trim());
            inputdata.setString(4, txtTANGGALLAHIR.getText().trim());
            inputdata.setString(5, txtALAMAT.getText().trim());
            inputdata.setString(6, txtFAKULTAS.getText().trim());
            inputdata.setString(7, txtJURUSAN.getText().trim());
            inputdata.setString(8, txtANGKATAN.getText().trim());
            inputdata.execute();
            JOptionPane.showMessageDialog(null,"Data Berhasil di Simpan.", "PEMBERITAHUAN", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (final SQLException | InstantiationException | IllegalAccessException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Data Gagal di Simpan.", "PEMBERITAHUAN", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTambahDataActionPerformed

    private void txtTANGGALLAHIRFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTANGGALLAHIRFocusGained
        // TODO add your handling code here:
        if(txtTANGGALLAHIR.getText().equals("*1999-11-09")) {
            txtTANGGALLAHIR.setText("");
        }
        txtTANGGALLAHIR.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtTANGGALLAHIRFocusGained

    private void txtTANGGALLAHIRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTANGGALLAHIRFocusLost
        // TODO add your handling code here:
        if(txtTANGGALLAHIR.getText().equals("")) {
            txtTANGGALLAHIR.setText("*1999-11-09");
        }
        txtTANGGALLAHIR.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_txtTANGGALLAHIRFocusLost

    private void btnUbahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahDataActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            final String username = "root";
            final String password = "";
            final Connection koneksi = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/latihan_db", username, password);
            
            System.out.println("Koneksi Berhasil");
            
            String NIM = txtNIM.getText();
            String NAMA = txtNAMA.getText();
            String jeniskelamin = null;
            if (rbL.isSelected()){
                jeniskelamin = rbL.getText();
            } else {
                jeniskelamin = rbP.getText();
            }
            String JENISKELAMIN = jeniskelamin;
            String TANGGALLAHIR = txtTANGGALLAHIR.getText();
            String ALAMAT = txtALAMAT.getText();
            String FAKULTAS = txtFAKULTAS.getText();
            String JURUSAN = txtJURUSAN.getText();
            String ANGKATAN = txtANGKATAN.getText();
            if(NIM.length()==9){
                String edit = "UPDATE biodata_mhs SET nim='"+NIM+"',"
                        + "nama='"+NAMA+"',"
                        + "jenis_kelamin='"+jeniskelamin+"',"
                        + "tanggal_lahir='"+TANGGALLAHIR+"',"
                        + "alamat='"+ALAMAT+"',"
                        + "fakultas='"+FAKULTAS+"',"
                        + "jurusan='"+JURUSAN+"',"
                        + "angkatan='"+ANGKATAN+"' WHERE nim='"+NIM+"'";
                PreparedStatement editdata = koneksi.prepareStatement(edit);
                editdata.execute();
                JOptionPane.showMessageDialog(null,"Data Berhasil di Ubah.", "PEMBERITAHUAN", JOptionPane.INFORMATION_MESSAGE);
            } else if (NIM.isEmpty())
                JOptionPane.showMessageDialog(null,"NIM tidak boleh kosong.", "PEMBERITAHUAN", JOptionPane.ERROR_MESSAGE);
            else {
                JOptionPane.showMessageDialog(null,"NIM Anda Salah.", "PEMBERITAHUAN", JOptionPane.ERROR_MESSAGE);
            }
        } catch (final SQLException | InstantiationException | IllegalAccessException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Data Gagal di Ubah.", "PEMBERITAHUAN", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUbahDataActionPerformed

    private void btnHapusDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusDataActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            final String username = "root";
            final String password = "";
            final Connection koneksi = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/latihan_db", username, password);
            
            System.out.println("Koneksi Berhasil");
            
            String hapus = "DELETE FROM biodata_mhs WHERE nim = ?";
            PreparedStatement hapusdata = koneksi.prepareStatement(hapus);
            hapusdata.setString(1, txtNIM.getText());
            hapusdata.execute();
            JOptionPane.showMessageDialog(null,"Data Berhasil di Hapus.", "PEMBERITAHUAN", JOptionPane.INFORMATION_MESSAGE);
        } catch (final SQLException | InstantiationException | IllegalAccessException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Data Gagal di Hapus.", "PEMBERITAHUAN", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
        
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            final String username = "root";
            final String password = "";
            final Connection koneksi = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/latihan_db", username, password);
            System.out.println("Koneksi Berhasil");
        } catch (final SQLException | InstantiationException | IllegalAccessException | ClassNotFoundException ex) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<aplikasidatabase.BiodataMhs> biodataMhsList;
    private javax.persistence.Query biodataMhsQuery;
    private javax.swing.JButton btnHapusData;
    private javax.swing.JButton btnTambahData;
    private javax.swing.JButton btnUbahData;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbL;
    private javax.swing.JRadioButton rbP;
    private javax.swing.JTable tblBiodatamhs;
    private javax.swing.JTextField txtALAMAT;
    private javax.swing.JTextField txtANGKATAN;
    private javax.swing.JTextField txtFAKULTAS;
    private javax.swing.JTextField txtJURUSAN;
    private javax.swing.JTextField txtNAMA;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtTANGGALLAHIR;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
